### ISSUE TITLE
mouse click: TypeError: [nut.js] - TypeError: A string was expected

### ISSUE THREAD

**Issue by Lieonkp** [ZachJW34/nut.js#1]
mouse.js

const { mouse, left } = require('@nut-tree-fork/nut-js');

mouse.config.autoDelayMs = 100;

async function performClick() {
    try {
        await mouse.click(left);
    } catch (err) {
        console.error('Error performing mouse click:', err);
    }
}

performClick();

------------------------------------------------------------------------------

Error performing mouse click: TypeError: [nut.js] - TypeError: A string was expected
    at D:\Documents\botsepf\node_modules\@nut-tree-fork\libnut\dist\lib\libnut-mouse.class.js:39:40
    at new Promise (<anonymous>)
    at MouseAction.click (D:\Documents\botsepf\node_modules\@nut-tree-fork\libnut\dist\lib\libnut-mouse.class.js:37:16)
    at MouseClass.click (D:\Documents\botsepf\node_modules\@nut-tree-fork\nut-js\dist\lib\mouse.class.js:240:52)
    at async performClick (D:\Documents\botsepf\mouse.js:8:9)

------------------------------------------------------------------------------
node -v
v20.15.1
npm -v
10.7.0

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045

**Comment by smithkyle** [comment]
You need to use:
```mouse.leftClick()```
Or you need to add ```Button```
To your import and do: ```mouse.click(Button.LEFT)```
